# Generated by Django 3.2 on 2021-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_id", models.IntegerField()),
                ("seller_product_name", models.CharField(max_length=50)),
                ("stock_status", models.CharField(max_length=50)),
                ("price_incl_shipping", models.FloatField()),
                ("price_excl_shipping", models.FloatField()),
                ("seller_id", models.IntegerField()),
                ("seller_name", models.CharField(max_length=50)),
                ("seller_rating", models.FloatField()),
                ("product_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_number", models.IntegerField()),
                ("product_name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
