# Generated by Django 3.2 on 2021-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prisjakt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="price_incl_shipping",
            field=models.FloatField(null=True),
        ),
    ]
