# Generated by Django 3.2 on 2021-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prisjakt", "0002_alter_prices_price_incl_shipping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prices",
            name="id",
        ),
        migrations.RemoveField(
            model_name="products",
            name="id",
        ),
        migrations.AlterField(
            model_name="prices",
            name="price_excl_shipping",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="prices",
            name="price_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="prices",
            name="seller_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="prices",
            name="seller_product_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="prices",
            name="seller_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="prices",
            name="stock_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
