# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

matrix:
  include:
    - stage: Test
      python: '3.8'
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script:
        - pytest --cov-report xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: Deploy
      script:
        - pipenv run python manage.py migrate
        - pipenv run python -m final_project


stages:
  - Test
  - name: Deploy
    if: branch = master


before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

install:
  - pipenv install --dev --ignore-pipfile --deploy
