# Generated by Django 3.2 on 2021-04-26 14:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prisjakt", "0003_auto_20210426_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="prices",
            name="timestamp",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
