# Generated by Django 3.2 on 2021-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prisjakt", "0005_auto_20210426_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="unique_identifier",
            field=models.CharField(
                blank=True, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
